### ISSUE TITLE
Trusting this python app?

### ISSUE THREAD

**Issue by paulsblackfriday** [stanfortonski/Tinder-Bot#16]
HI how are we supposed to trust this app is actually for tinder, when the first thing it wants is our gmail (google) login account?
even still today TR works with just a gmail login opposed to a fb login (?) Is there some sort of sample you can post in the GITHUB asap which shows in video demo that guarantees the process directs towards TR with proper login for testing this for developer learning?

**Comment by stanislawfortonski** [comment]
First of all code is available in open source so you can check exactly all code. That makes this trustful. You don't have to use that.
