### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by JKryba** [stanfortonski/Tinder-Bot#6]
Podczas momentu, w którym program powinien się zalogować na tindera otrzymuję błąd:
"selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/div[2]/div/div/div[1]/div/div[3]/span/div[2]/button"
Próbowałem na pythonie: 3.9.0 / 3.9.1 / 2.7.0.
Robię to na wersji bota 1.6.1

**Comment by stanfortonski** [comment]
Witam, sprawdziłem czy znowu coś zmienili. Mi normalnie sie loguje. Spróbuj może zadziała za którymś razem. Możesz pobrać najnowszą wersję 1.6.2.
