### ISSUE TITLE
Tinder login

### ISSUE THREAD

**Issue by JKryba** [stanfortonski/Tinder-Bot#9]
Dzięki nowej wersji program nie upada w momencie logowanie do tindera. Tym razem problemem jest okno, które potrzebuję interakcji. 
![ed064da1681ab5eaad06b0422306377a](https://user-images.githubusercontent.com/75804873/101986803-80469a80-3c90-11eb-9bba-1163376fca6f.png)
Po tym oknie pojawia się błąd:
Error: Failed to login to Tinder. Check your data or try later.

Pozdrawiam oraz dziękuję za poświęcony czas.

**Comment by stanfortonski** [comment]
Musisz mieć konto Tinder powiązane z Facebookiem.
